spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plamilhasdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Pode trocar para validate se usar Flyway
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false       # Desative por enquanto até garantir a conexão

server:
  port: 8080

